on: ["push", "pull_request"]

name: Test in workspace

jobs:

  test-coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - uses: actions/checkout@v3
      with:
        repository: biothings/biothings_explorer
        ref: ${{ steps.branch-name.outputs.current_branch }}

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: pnpm install, generate coverage report
      run: |
        pnpm run clone
        pnpm run git checkout ${{ steps.branch-name.outputs.current_branch }}
        pnpm i
        pnpm run test-cov

    - name: Send coverage report to codecov for visualization
      uses: codecov/codecov-action@v3
      with:
        # working-directory: ./packages/@biothings-explorer/bte-trapi
        files: ./coverage/lcov.info
        verbose: true
