on: ["push", "pull_request"]

name: Test with workspace

jobs:

  test-coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        repository: biothings/bte-trapi-workspace

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: npm install, generate coverage report
      run: |
        npm run clone
        npm i || true && npm i
        npm run test-cov --workspace=@biothings-explorer/bte-trapi
